steps:
  - \FriendsOfWp\DeveloperCli\Boilerplate\Step\InitializeStep
  - \FriendsOfWp\DeveloperCli\Boilerplate\Step\CopyTemplatesStep
  - \FriendsOfWp\DeveloperCli\Boilerplate\Step\PrepareAdminStep
  - \FriendsOfWp\DeveloperCli\Boilerplate\Step\ReplacingPlaceholdersStep
  - \FriendsOfWp\DeveloperCli\Boilerplate\Step\RenameMasterFileStep
  - \FriendsOfWp\DeveloperCli\Boilerplate\Step\RenamePluginDirStep
