name: Release new Version

on:
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          ini-values: phar.readonly=0
          tools: composer
          coverage: none

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v2

      - name: Download box.phar
        run: |
          wget https://github.com/box-project/box/releases/download/4.3.8/box.phar  -P /tmp/

      - name: Run box builder
        run: |
          php /tmp/box.phar compile

      - name: Move phar file to temp directory
        run: |
          mv bin/wp-dev.phar /tmp

      - name: Show content of /tmp
        run: |
          ls /tmp         

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
            repo_token: ${{ secrets.GITHUB_TOKEN }}
            file: /tmp/wp-dev.phar
            asset_name: ${{ matrix.asset_name }}
            tag: ${{ github.ref }}
